/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package gradle.test

import org.apache.commons.math3.util.MathUtils

public class Library {
    public fun someLibraryMethod(): Boolean {
        val a = MathUtils.hash(33.333)
        println(a)
        return true
    }
}

/**
 * hello 哈
 */
public const val HELLO_KOTLIN = "Hello"